SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `payMyBuddyDB`;
USE `payMyBuddyDB`;

DROP TABLE IF EXISTS `Users`;
CREATE TABLE `Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL DEFAULT(`email`),
  `balance` DOUBLE NOT NULL DEFAULT 0,
  `bank_account_number` VARCHAR(45) NOT NULL DEFAULT ''
);

DROP TABLE IF EXISTS `Transactions`;
CREATE TABLE `Transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `type` ENUM('user', 'bank') NOT NULL,
  `amount` DOUBLE NOT NULL,
  `date` DATETIME NOT NULL DEFAULT LOCALTIME,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  FOREIGN KEY (`sender_id`) REFERENCES `Users`(`user_id`),
  FOREIGN KEY (`receiver_id`) REFERENCES `Users`(`user_id`)
);

DROP TABLE IF EXISTS `Connections`;
CREATE TABLE `Connections` (
  `connection_id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `date` DATETIME NOT NULL DEFAULT LOCALTIME,
  `id_initiator` INT NOT NULL,
  `id_target` INT NOT NULL,
  FOREIGN KEY (`id_initiator`) REFERENCES `Users`(`user_id`),
  FOREIGN KEY (`id_target`) REFERENCES `Users`(`user_id`)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
